version: '3'

services:
  database:
    container_name: "PI_DB"
    image: mysql
    environment:
      MYSQL_USER: "wave"
      MYSQL_DATABASE: "pi"
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - D:\Digital House\P.I
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge